# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b43998be44e4a2e03f59d62692c37d4f384deb6a94671dd88164794c90075f264f7848716e7b0f088f7526b6fcc694f9813c2912b4bb4336051c1f856d057fa4

test:
  secret_key_base: 30f4351276847fe8d5d55aa643dae3cc1c92c9b3b1b4f30f50cd2c129329656c349f29b5cd369c97279e45fc017a28d6165cc705397e01a0981d53cc91c6d38e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
